# Generated by Django 4.2.5 on 2023-11-25 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='end_junction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_junction_prices', to='booking_summary.junction'),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='start_junction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_junction_prices', to='booking_summary.junction'),
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
